In [26]:
import random
import math

import numpy as np

In [25]:
# --- Grid dimensions ---
WIDTH = 320
HEIGHT = 240

# --- Number of particles ---
NUM_PARTICLES = 2000

# --- Trail parameters ---
DEPOSIT_AMOUNT = 5.0
DECAY_FACTOR = 0.99

# --- Sensor parameters ---
SENSOR_ANGLE = math.radians(45)
SENSOR_DISTANCE = 3
ROTATION_ANGLE = math.radians(45)

# --- Display ---
PIXEL_SCALE = 4  # each grid cell = PIXEL_SCALE x PIXEL_SCALE screen pixels
SCREEN_WIDTH = WIDTH * PIXEL_SCALE
SCREEN_HEIGHT = HEIGHT * PIXEL_SCALE
FPS = 60

In [ ]:

def spawn_random():
    px = np.array([random.uniform(0, WIDTH) for _ in range(NUM_PARTICLES)])
    py = np.array([random.uniform(0, HEIGHT) for _ in range(NUM_PARTICLES)])
    ph = np.array([random.uniform(0, 2 * math.pi) for _ in range(NUM_PARTICLES)])

    return (px, py, ph)


def spawn_ring():
    cx, cy = WIDTH / 2, HEIGHT / 2
    radius = min(WIDTH, HEIGHT) * 0.35
    particles = []

    for i in range(NUM_PARTICLES):
        angle = 2 * math.pi * i / NUM_PARTICLES
        x = cx + math.cos(angle) * radius
        y = cy + math.sin(angle) * radius
        heading = angle + math.pi
        particles.append({"x": x, "y": y, "h": heading})

    px = np.array([p["x"] for p in particles])
    py = np.array([p["y"] for p in particles])
    ph = np.array([p["h"] for p in particles])

    return (px, py, ph)


def spawn_center():
    cx, cy = WIDTH / 2, HEIGHT / 2

    px = np.array([cx + random.gauss(0, 2) for _ in range(NUM_PARTICLES)])
    py = np.array([cy + random.gauss(0, 2) for _ in range(NUM_PARTICLES)])
    ph = np.array([random.uniform(0, 2 * math.pi) for _ in range(NUM_PARTICLES)])

    return (px, py, ph)


def spawn_clusters():
    particles = []
    for _ in range(NUM_PARTICLES // 2):
        particles.append(
            {
                "x": WIDTH * 0.25 + random.gauss(0, 2),
                "y": HEIGHT / 2 + random.gauss(0, 2),
                "heading": random.uniform(0, 2 * math.pi),
            }
        )
    for _ in range(NUM_PARTICLES - NUM_PARTICLES // 2):
        particles.append(
            {
                "x": WIDTH * 0.75 + random.gauss(0, 2),
                "y": HEIGHT / 2 + random.gauss(0, 2),
                "heading": random.uniform(0, 2 * math.pi),
            }
        )

    px = np.array([p["x"] for p in particles])
    py = np.array([p["y"] for p in particles])
    ph = np.array([p["h"] for p in particles])

    return (px, py, ph)


def create_trail_map():
    return np.zeros((HEIGHT, WIDTH), dtype=np.float64)

def decay(trail_map):
    trail_map *= DECAY_FACTOR


(array([225.52329948, 175.65624733, 312.31691998, ..., 247.78935517,
         11.31182004, 292.83199381], shape=(2000,)),
 array([210.55675915, 169.36588551,  72.33799999, ..., 162.27317709,
        165.74304878, 150.46370504], shape=(2000,)),
 array([1.9324207 , 1.76075861, 5.81162635, ..., 3.65348227, 2.84155519,
        0.19519029], shape=(2000,)))

In [ ]:
trail_map = np.zeros((10, 10))

# Three particles, all at the same cell (2, 3)
ys = np.array([2, 2, 2])
xs = np.array([3, 3, 3])

trail_map[ys, xs] += 5.0 # Gotcha!!! 

print(trail_map[2, 3])  # 5.0  — NOT 15.0!



5.0


In [28]:
trail_map = np.zeros((10, 10))

# Three particles, all at the same cell (2, 3)
ys = np.array([2, 2, 2])
xs = np.array([3, 3, 3])

np.add.at(trail_map, (ys, xs), 5.0)

print(trail_map[2, 3])


15.0
